import Hero from "../../Components/Hero";
import About from "../../Components/about";
import Skills from "../../Components/skills";
import Projects from "../../Components/projects";
import Contact from "../../Components/contact";

import Head from "next/head";

const Home = () => {
  return (
    <>
      <Head>
        <title>Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div>
          <Hero />
          <About />
          <Skills />
          <Projects />
          <Contact />
        </div>
    </>
  );
}

export default Home;